cc_library(
    name = "basic_board",
    srcs = ["basic_board.hpp"],
    # hdrs = ["hello-greet.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//engine/board_v1.0/general:chess-basic",
    ],
)